// importing global styling
import "bootstrap/dist/css/bootstrap.css";
import "@/styles/bootstrap.scss";
import '@/styles/globals.scss';

//importing components
import BootstrapInitializer from "@/components/BootstrapInitializer";
import Header from "@/template/Header";
import { Roboto } from "next/font/google";
import { ReactNode } from "react";
import { UserContextProvider } from "@/context/UserContextProvider";


// Configure Roboto font
const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  weight: ["100","300","400","500"], // Adjust weights as needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// Define the type for props
interface RootLayoutProps {
  children: ReactNode;
}


export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={roboto.className}>
      <Header />
     <UserContextProvider>
      {children}
      </UserContextProvider>
      <BootstrapInitializer/>
      </body>
    </html>
  );
}